# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
  - minitest/ruby_event_store
includes:
  - lib
integration: minitest
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - Minitest::RubyEventStore*
