language: ruby
rvm:
- 2.1.10
- 2.2.5
- 2.3.1
before_install: gem install bundler
gemfile: Gemfile
script: make mutate
notifications:
  slack:
    secure: i/GM4u6oCfgdt9ablmOx4ov3Y9bHJjHabXxWXt+GLRlfW5MDdzwEH0QOx2mveVbit+00rKKqZzBAbEQ1yLo4MLLovHyJvCzoluC10u0MRIR7e8ZlCdlww+IL3JmD8E7G1a/fKEMoKwfLrYUXa5K0oAeKpJ3RwP+tTD+g3KxQfIA=
env:
  - CODECLIMATE_REPO_TOKEN=24ac54c50ae022eb008ebd1f1e5da043d6419759136d4027d0266426c6198ef2
