version: 2
updates:
- package-ecosystem: bundler
  directory: /railseventstore.org
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /railseventstore.org
  schedule:
    interval: daily

- package-ecosystem: elm
  directory: /ruby_event_store-browser/elm
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /ruby_event_store-browser/elm
  schedule:
    interval: daily

