AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - ruby_event_store-active_record/active_record/lib/ruby_event_store/active_record/generators/templates/*
    - bounded_context/lib/generators/templates/*
    - support/helpers/0_18_2_migration_template.rb
    - contrib/**/*
    - railseventstore.org/**/*
    - bounded_context/spec/dummy_*/**/*
    - "**/bin/*"
    - ruby_event_store-browser/elm/node_modules/**/*

Lint/UselessAssignment:
  Exclude:
    - ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
    - "**/spec/*"

Lint/SuppressedException:
  Enabled: false