language: ruby
matrix:
  include:
  - rvm: 2.4.1
    env: TARGET=bounded_context SCRIPT=mutate
  - rvm: 2.4.1
    env: TARGET=rails_event_store-rspec SCRIPT=mutate
  - rvm: 2.4.1
    env: TARGET=aggregate_root SCRIPT=mutate
  - rvm: 2.4.1
    env: TARGET=ruby_event_store SCRIPT=mutate
  - rvm: 2.4.1
    env: TARGET=rails_event_store SCRIPT=mutate
  - rvm: 2.4.1
    env: 'TARGET=rails_event_store_active_record SCRIPT=mutate DATABASE_URL=sqlite3::memory:'
  - rvm: 2.3.4
    env: TARGET=bounded_context SCRIPT=test
  - rvm: 2.3.4
    env: TARGET=rails_event_store-rspec SCRIPT=test
  - rvm: 2.3.4
    env: TARGET=aggregate_root SCRIPT=test
  - rvm: 2.3.4
    env: TARGET=ruby_event_store SCRIPT=test
  - rvm: 2.3.4
    env: TARGET=rails_event_store SCRIPT=test
  - rvm: 2.2.7
    env: TARGET=bounded_context SCRIPT=test
  - rvm: 2.2.7
    env: TARGET=rails_event_store-rspec SCRIPT=test
  - rvm: 2.2.7
    env: TARGET=aggregate_root SCRIPT=test
  - rvm: 2.2.7
    env: TARGET=ruby_event_store SCRIPT=test
  - rvm: 2.2.7
    env: TARGET=rails_event_store SCRIPT=test
  - rvm: 2.2.7
    env: "TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=sqlite3:db.sqlite3"
  - rvm: 2.3.4
    env: "TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=sqlite3:db.sqlite3"
  - rvm: 2.4.1
    env: TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=postgres://localhost/rails_event_store_active_record?pool=5
  - rvm: 2.4.1
    env: TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=mysql2://root:@127.0.0.1/rails_event_store_active_record?pool=5
  - rvm: 2.4.1
    env: TARGET=rails_event_store SCRIPT=test RAILS_VERSION=5.1.4
  - rvm: 2.4.1
    env: TARGET=rails_event_store SCRIPT=test RAILS_VERSION=5.0.6
  - rvm: 2.4.1
    env: TARGET=rails_event_store SCRIPT=test RAILS_VERSION=4.2.10
  - rvm: 2.4.1
    env: TARGET=bounded_context SCRIPT=test RAILS_VERSION=5.1.4
  - rvm: 2.4.1
    env: TARGET=bounded_context SCRIPT=test RAILS_VERSION=5.0.6
  - rvm: 2.4.1
    env: TARGET=bounded_context SCRIPT=test RAILS_VERSION=4.2.10
  - rvm: 2.4.1
    env: TARGET=rails_event_store-rspec SCRIPT=test RAILS_VERSION=5.1.4
  - rvm: 2.4.1
    env: TARGET=rails_event_store-rspec SCRIPT=test RAILS_VERSION=5.0.6
  - rvm: 2.4.1
    env: TARGET=rails_event_store-rspec SCRIPT=test RAILS_VERSION=4.2.10
  - rvm: 2.4.1
    env: TARGET=aggregate_root SCRIPT=test RAILS_VERSION=5.1.4
  - rvm: 2.4.1
    env: TARGET=aggregate_root SCRIPT=test RAILS_VERSION=5.0.6
  - rvm: 2.4.1
    env: TARGET=aggregate_root SCRIPT=test RAILS_VERSION=4.2.10
  - rvm: 2.4.1
    env: TARGET=ruby_event_store SCRIPT=test RAILS_VERSION=5.1.4
  - rvm: 2.4.1
    env: TARGET=ruby_event_store SCRIPT=test RAILS_VERSION=5.0.6
  - rvm: 2.4.1
    env: TARGET=ruby_event_store SCRIPT=test RAILS_VERSION=4.2.10
  - rvm: 2.4.1
    env: "TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=sqlite3:db.sqlite3 RAILS_VERSION=5.1.4"
  - rvm: 2.4.1
    env: "TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=sqlite3:db.sqlite3 RAILS_VERSION=5.0.6"
  - rvm: 2.4.1
    env: "TARGET=rails_event_store_active_record SCRIPT=test DATABASE_URL=sqlite3:db.sqlite3 RAILS_VERSION=4.2.10"

before_script:
- psql -c 'create extension pgcrypto;' -U postgres
- psql -c 'create database rails_event_store_active_record;' -U postgres
- mysql -e 'CREATE DATABASE rails_event_store_active_record;'
before_install: gem install bundler
gemfile: "$TARGET/Gemfile"
script: make -C $TARGET install $SCRIPT
services:
- postgresql
- mysql
addons:
  postgresql: '9.6'
notifications:
  slack:
    secure: bWHujiF+SFAh6m3aXxtLpsyiSfYGPQAGHwp/nsv8VpXxzON1evYkyJ+Fu+vPjvyFrA8m6N9E/jmzEGOMMvOXT0++SR4Axr7LhsbFdBDhlRBgtkzEV1Iyr96ipaTQ1IwY2R0QnVdFSIbxKtJAtB1BFn4tBxDEfLc44/n0+7SxEY8=
