[build]
  base = "railseventstore.org/"
  command = "./bin/build"
  publish = "build/"

[build.environment]
  NODE_VERSION = "12.16.1"
  RUBY_VERSION = "2.6.2"

[[redirects]]
  from = "/docs/*"
  to = "/docs/v1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/new"
  to = "https://raw.githubusercontent.com/RailsEventStore/rails_event_store/master/APP_TEMPLATE"
  status = 301
  force = false
