[build]
  base = "railseventstore.org/"
  command = "./bin/build"
  publish = "build/"
  ignore  = "false"

[build.environment]
  NODE_VERSION = "12.16.1"
  RUBY_VERSION = "2.6.2"

[[redirects]]
  from = "http://www.railseventstore.org/*"
  to = "https://railseventstore.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/*"
  to = "/docs/v2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/new"
  to = "https://raw.githubusercontent.com/RailsEventStore/rails_event_store/master/APP_TEMPLATE"
  status = 301
  force = false

