# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 189d18e5846da219bcd78462adc978d417900a989e78abbf7b2db03d4b492fc0d7f69bb45ad98553e459f1a4f4959def63bfe6a6f3b6a202988ddcf084ee3ba3

test:
  secret_key_base: b19a266a446a292c0d59503b7df28dc4baa2597c3cf920da2b0b39e34ca3ab5ce36ab7739e586de06506623713a1aed2378e04fc20602bcc1a604645d8b2b066

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
