version: 2
jobs:
  aggregate_root:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
    steps:
      - checkout
      - run: cd aggregate_root && make install mutate

  rails_event_store-browser:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
    steps:
      - checkout
      - run: cd rails_event_store-browser && make install mutate

  rails_event_store_active_record:
    macos:
      xcode: "9.3.0"
    steps:
      - run: brew install mysql
      - run: brew install sqlite3
      - run: brew install postgresql
      - checkout
      - run: cd rails_event_store_active_record && make install mutate

workflows:
  version: 2
  test_mutate:
    jobs:
#    - aggregate_root
#    - rails_event_store-browser
    - rails_event_store_active_record