# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
  - ruby_event_store/sidekiq_scheduler
includes:
  - lib
integration: rspec
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - RubyEventStore::SidekiqScheduler*
