name: aggregate_root
on:
  push:
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: aggregate_root
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
          - ruby: ruby-2.6
            gemfile: Gemfile
            os: ubuntu-20.04
          - ruby: ruby-2.5
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: aggregate_root
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}


name: coverage
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          - gem: aggregate_root
          - gem: rails_event_store_active_record
          - gem: ruby_event_store-rspec
          - gem: rails_event_store
          - gem: ruby_event_store-browser
          - gem: ruby_event_store
    steps:
      - uses: actions/checkout@v2
      - run: test -e Gemfile.lock
        working-directory: ${{ matrix.gem }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-2.7
          bundler-cache: true
          working-directory: ${{ matrix.gem }}
      - run: make mutate
        working-directory: ${{ matrix.gem }}
