name: multiple_databases_repository_sample_app
on:
  schedule:
    - cron: "0 17 * * *"
  push:
    paths:
      - "contrib/multiple_databases_repository_sample_app/**"
  pull_request:
    paths:
      - "contrib/multiple_databases_repository_sample_app/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      LOCATION: contrib/multiple_databases_repository_sample_app
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.LOCATION }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.LOCATION }}
      - run: bin/rspec
        working-directory: ${{ env.LOCATION }}
