name: ruby_event_store-outbox
on:
  schedule:
    - cron: "0 17 * * *"
  push:
    paths:
      - "contrib/ruby_event_store-outbox/**"
  pull_request:
    paths:
      - "contrib/ruby_event_store-outbox/**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      GEM_NAME: ruby_event_store-outbox
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      GEM_LOCATION: contrib/ruby_event_store-outbox
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_6_0
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_5_2
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.6
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.5
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_LOCATION }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_LOCATION }}
      - run: make test
        working-directory: ${{ env.GEM_LOCATION }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      GEM_NAME: ruby_event_store-outbox
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      GEM_LOCATION: contrib/ruby_event_store-outbox
      REDIS_URL: redis://localhost:6379/0
      MUTANT_JOBS: 1
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: "sqlite3::memory:"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_LOCATION }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_LOCATION }}
      - run: make mutate-changes
        working-directory: ${{ env.GEM_LOCATION }}
