name: ruby_event_store-transformations_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-transformations/Gemfile.lock"
      - ".github/workflows/ruby_event_store-transformations_coverage.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-transformations/Gemfile.lock"
      - ".github/workflows/ruby_event_store-transformations_coverage.yml"
      - "support/**"
jobs:
  mutate:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-transformations
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.1
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate
        working-directory: ${{ env.WORKING_DIRECTORY }}
